### PR TITLE
Fix issue #10 and a bunch of other stuff

### LINKED ISSUE #10: Randomly cannot ping or connect to server
While running a server under mineginx, sometimes minginx just never can be pinged by a client. This happens randomly even when there are clients already connected and are able to ping the server.

Nothing in the logs say anything, proxy is up and running and not crashing.

### PR DESCRIPTION
**Pull request by Kaydax**
Here is a bunch of changes that fix #10 and also fixes a random crash that happens. Also improve the code base to be way more robust.

I was sent down a rabbit hole because of the fact I forgot to up the file descriptor limit on my proxy server that sits between cloudflare and mineginx, thus causing connection limits

List of changes so far:
- Fixed buffer expansion panic (`todo!()` → actual implementation)
- Fixed off-by-one in buffer data length calculation
- Fixed packet data length check after reading packet ID
- Fixed string reader bounds check and UTF-8 panic
- Added panic logging for spawned tasks
- Replaced `.unwrap()` calls in main with error handling
- Fixed TCP connections not sending FIN on close
- Ensured forwarding tasks are awaited before cleanup
- Fixed domain matching to handle trailing dots and case differences
- Set global panic hook for crash diagnostics
- Used socket2 for TCP listener with 1024 backlog and SO_REUSEADDR

### CODE REVIEW

File: mineginx/src/main.rs [hunk 1]
```diff
@@ -54,75 +75,104 @@ async fn handle_client(mut client: TcpStream, config: Arc<MineginxConfig>) {
...
         }
     };
 
-    info!("new connection (protocol_version: {}, domain: {}, upstream: {})", &handshake.protocol_version, &domain, upstream_server.proxy_pass);
+    // Look up the pre-resolved address, or try resolving on-the-fly
+    // for upstreams that weren't available at startup
+    let upstream = {
+        let cache = resolved.read().await;
+        cache.get(&server_desc.proxy_pass).cloned()
+    };
```
Comment (Folleach) [inline mineginx/src/main.rs]: This behavior will cause the address to be cached indefinitely, meaning the proxy would have to be restarted to update the DNS. I try to avoid reasons for restarting the proxy server, so I would prefer to get rid of the cache.
Considering that currently the asynchronous `lookup_host` from tokio is used

File: mineginx/src/main.rs [hunk 2]
```diff
@@ -1,21 +1,44 @@
...
+}
+
+/// Try to resolve an upstream hostname to a SocketAddr asynchronously.
+/// Uses a 2-second timeout to avoid blocking startup or connections.
+async fn try_resolve(proxy_pass: &str) -> Option<SocketAddr> {
+    match timeout(Duration::from_secs(2), tokio::net::lookup_host(proxy_pass)).await {
+        Ok(Ok(mut addrs)) => addrs.next(),
+        _ => None,
+    }
+}
```
Comment (Folleach) [inline mineginx/src/main.rs]: I know that 2 seconds for a DNS lookup is more than enough, but time is a relative metric. Some environments might require more time to resolve an address. Hardcoding this value could make the server completely non-functional in such cases. Should we move this timeout to the configuration and keep 2 seconds as the default?

File: mineginx/src/main.rs [hunk 3]
```diff
@@ -54,75 +75,104 @@ async fn handle_client(mut client: TcpStream, config: Arc<MineginxConfig>) {
...
-        client_writer,
-        if let Some(buffer_size) = upstream_server.buffer_size { buffer_size  as usize } else { 2048 });
+    let (upstream_reader, upstream_writer) = upstream_conn.into_split();
+    let buf_size = upstream.buffer_size.map(|b| b as usize).unwrap_or(8192);
+
+    // Each direction gets its own spawned task so the tokio scheduler
+    // can freely interleave them with the accept loop and other connections.
+    // When one direction reads EOF it calls shutdown() on its writer,
+    // sending FIN to the remote — the opposite task then naturally reads
+    // EOF from its side and terminates. No explicit signaling needed.
```
Comment (Folleach) [inline mineginx/src/main.rs]: I'm not a big fan of Unicode characters in source code. Sure, it's not an issue for modern text editors, they all handle UTF-8 and other encodings just fine, but I'd still prefer to keep the code free of hard-to-type characters. Shall we remove them?
Image

File: mineginx/src/main.rs [hunk 4]
```diff
@@ -207,20 +263,88 @@ async fn main() -> ExitCode {
...
+        }
+        if let Err(e) = socket.bind(&addr.into()) {
+            error!("failed to bind {}: {e}", &server.listen);
+            return ExitCode::from(3);
+        }
+        // Set backlog to 1024 to handle bursts of connections
+        if let Err(e) = socket.listen(1024) {
+            error!("failed to listen on {}: {e}", &server.listen);
+            return ExitCode::from(3);
+        }
```
Comment (Folleach) [inline mineginx/src/main.rs]: Some comments seem redundant. I don't really like it when comments just repeat the code in different words

**Review by Folleach — CHANGES_REQUESTED** [review]
Wow, that is so many changes you've made! Hello!

Most of these improvements are spot on and really make sense. 
I grateful how you rewrote `forward_stream` function, it was awfuuuul, haha. I wrote it one evening after falling down a rabbit hole and told myself: "Will rewrite this someday", and now you've simplified it so much. Thanks a lot!

I've had a quick look at the code, and there are a few bits I'd like to tweak. If you could make those changes, that'd be awesome. Or I can handle it myself later when I have some free time.
Either way, this is a great improvements to the code base!

File: mineginx/src/main.rs (hunk 1 above)
Comment (Folleach) [reply mineginx/src/main.rs]: I want to believe that operating systems can handle the cache themselves

**Comment by Kaydax** [comment]
@Folleach I removed the DNS cache as it really was only there as a test to see if DNS resolution under docker was causing some weird issue with the pinging problems I was having. I also removed all the redundant comments and simplified the huge comment

**Comment by Folleach** [comment]
Looks great.  
Now it is available on Docker Hub at the tag `v0.1.6`
